### ISSUE TITLE
[Chore] 초기 세팅

### ISSUE THREAD

**Issue by EunsuSeo01** [NOW-SOPT-APP6-BUBBLE/bubble-iOS#1]
## 🛠 Issue
합동 세미나 전, 깃허브 초기 세팅 및 프로젝트 초기 세팅을 진행합니다.

## 📝 To-do
- [x] 이슈 템플릿 적용
- [x] 이슈 Label 생성
- [x] PR 템플릿 적용
- [x] gitignore 적용
- [x] 커밋 템플릿 제작 - 적용은 각자
- [x] SwiftLint 세팅 - 적용은 각자
- [x] No storyboard 세팅
- [x] 기초 폴더링 작업
