### ISSUE TITLE
[Feat] Store Detail UI 구현

### ISSUE THREAD

**Issue by shimseohyun** [NOW-SOPT-APP6-BUBBLE/bubble-iOS#13]
## 🛠 Issue
> 이슈에 대해 간략하게 설명해주세요 (글, 사진)

Store Detail Page의 UI를 구현합니다.
|<img width="335" alt="스크린샷 2024-05-17 오후 9 23 12" src="https://github.com/NOW-SOPT-APP6-BUBBLE/bubble-iOS/assets/117021241/c9ac4476-b881-41fb-ad49-c9bb6678860e">|
|--|

## 📝 To-do
> 진행할 작업에 대해 자세히 적어주세요
- [x] 상단 information 부분 구현
- [x] 인원수에 맞춘 가격 표시 구현
- [x] 이용안내 동의 체크박스, 토글 구현
